phpfpm:
    build: php-fpm/
    volumes:
        - ..:/var/www/z-push:Z
nginx:
    build: nginx/
    volumes_from:
        - phpfpm
    links:
        - phpfpm:zpushphpfpm
    ports:
        - "80:80"
        - "443:443"
